management.security.enabled: false
demo.security.jwt:
  tokenExpirationTime: 15000 # Number of minutes
  refreshTokenExpTime: 60000 # Minutes
  tokenIssuer: http://${kinoman.host}
  tokenSigningKey: 7a50f044da25a0f071f3c3db105d9a02
spring:
  data:
    elasticsearch:
      cluster-nodes: ${kinoman.host}:9300
  datasource.dbcp2:
    driver-class-name: org.postgresql.Driver
    username: ${local.pg.user}
    password: ${local.pg.password}
    url: "jdbc:postgresql://${kinoman.host}:5432/dk"
    initial-size: 0
    max-total: 12
    max-idle: 12
  h2:
    console:
      enabled: true
      path: /search/console
      settings:
        trace: false
        web-allow-others: false
  servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB
  banner:
    location: banner.txt

###
#   H2 Settings
###
inh2:
  datasource:
    url: jdbc:h2:mem:kinoman
    username: kinoman
    password:
    driver-class-name: org.h2.Driver
    init-sql: h2.sql
#logging:
#  config: "classpath:log4j2.properties"

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json, application/xml,text/html,text/plain
#elasticsearch:
#  clustername : dpat
#  host : 192.168.0.50
#  port : 9300
#  nodename: dpat
#
rabbitmq:
  host: 192.168.0.50
  username: admin
  password: qazwsx123
  port: 5672

file.uploadDir: ./uploads





